using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Xunit;
using gaseous_server.Classes;
using System.Reflection;

namespace gaseous_server.Tests
{
    public class LoggingContextTests
    {
        /// <summary>
        /// Validates that ambient CallContext values (CorrelationId, CallingProcess, CallingUser)
        /// are captured into the LogItem generated by Logging.Log.
        /// This test injects a custom sink to observe the LogItem passed to WriteAsync.
        /// </summary>
        [Fact]
        public async Task Log_Captures_Ambient_Context_In_Disk_Output()
        {
            // Arrange: set ambient context
            string correlation = Guid.NewGuid().ToString();
            string process = "UnitTestProcess";
            string user = "unittest@example.com";
            CallContext.SetData("CorrelationId", correlation);
            CallContext.SetData("CallingProcess", process);
            CallContext.SetData("CallingUser", user);

            // Force disk logging so we can inspect file contents
            Logging.WriteToDiskOnly = true;
            string logFile = Config.LogFilePath;
            long initialLength = 0;
            if (File.Exists(logFile))
            {
                initialLength = new FileInfo(logFile).Length;
            }

            // Act
            Logging.Log(gaseous_server.Classes.Logging.LogType.Information, "TestComponent", "Context capture test");
            await Task.Delay(500); // allow async write

            // Assert: read new tail of file and ensure correlation id present
            Assert.True(File.Exists(logFile), "Log file should exist after logging");
            string fileContent = File.ReadAllText(logFile);
            Assert.Contains(correlation, fileContent);
            // CallingProcess may be normalized to ServerProcess if empty; ensure either ambient process or component present
            Assert.True(fileContent.Contains(process) || fileContent.Contains("TestComponent"), "Process should appear in log output");
        }
    }
}
